### ISSUE TITLE
My report about result of commit

### ISSUE THREAD

**Issue by SandraShn** [SandraShn/SITZOD--Shnaider-MainProject#1]
![screen2](https://user-images.githubusercontent.com/34454857/33852547-a5598d4c-dec3-11e7-964f-10685fbb4f11.jpg)
![scrin](https://user-images.githubusercontent.com/34454857/33852548-a57730f4-dec3-11e7-81ee-c97d59f0a7c4.jpg)

**Comment by smoktii-igov** [comment]
Ok
